modLoader="javafml"
loaderVersion="[41,)" #forge version dep
license="GNU Lesser General Public License v3.0"
issueTrackerURL="https://github.com/iChun/Ding/issues"

[[mods]]
    modId="ding"
    version="${file.jarVersion}" #mandatory
    displayName="Ding"
    displayURL="https://ichun.me/mods/ding/"
    authors="iChun"
    description='''
    Plays a sound once the client has loaded to the main menu or loaded the world
    '''

[[dependencies.ding]]
    modId="forge"
    mandatory=true
    versionRange="[41,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.ding]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"
